name: hexa-test
on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repo
      - uses: actions/setup-go@v5
        name: Setup Go with demo dir
        with:
          go-version: '^1.22'
          cache-dependency-path: |
            demo/go.sum
      - name: Run test
        run: |
          #./test_workspace.sh
          cd demo
          source ./.env_development
          go test -tags integration -coverprofile coverage.out  ./.../
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)