name: google-cloud
on:
  workflow_call:
jobs:
  google-container-demo:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
      - name: build-image
        run: |
          echo "wip"

  google-deploy-hexa-demo:
    runs-on: ubuntu-latest
    needs: [ google-container-demo ]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
      - name: build-image
        run: |
          echo "wip"

  google-container-open-policy-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
      - name: build-image
        run: |
          echo "wip"

  google-deploy-hexa-open-policy-agent:
    runs-on: ubuntu-latest
    needs: [ google-container-open-policy-agent ]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
      - name: build-image
        run: |
          echo "wip"

