name: google-cloud-demo
on:
  workflow_call:
jobs:
  google-container-demo:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: "authenticate to google cloud"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: 'access_token'
          workload_identity_provider: "${{ secrets.GOOGLE_FEDERATION_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GOOGLE_FEDERATION_SERVICE_ACCOUNT }}"
      - name: "set up cloud sdk"
        uses: "google-github-actions/setup-gcloud@v2"
      - id: "gcloud"
        name: "gcloud"
        run: |
          gcloud builds submit --pack image=${{secrets.GOOGLE_ARTIFACT}}:${{ github.sha }},builder=heroku/buildpacks:20

  google-deploy-hexa-demo:
    runs-on: ubuntu-latest
    needs: [ google-container-demo ]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: build-image
        run: |
          echo "wip"

  google-container-open-policy-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: build-image
        run: |
          echo "wip"

  google-deploy-hexa-open-policy-agent:
    runs-on: ubuntu-latest
    needs: [ google-container-open-policy-agent ]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: build-image
        run: |
          echo "wip"

